repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.1.1
    hooks:
      - id: ansible-lint
        files: \.(yml)$
