- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
  - config

- name: Add aliases to .zshrc
  blockinfile:
    block: "{{ lookup('file', 'zshrc.aliases') }}"
    path: ~/.zshrc
