- name: dotfiles dirs
  file:
    path: "~/.{{ item }}"
    state: directory
  loop:
    - config

- name: Add aliases to .zshrc
  blockinfile:
    block: "{{ lookup('file', 'zshrc.aliases') }}"
    path: ~/.zshrc
    marker: "# {mark} ALIASES BLOCK"

- name: Add custom config to .zshrc
  lineinfile:
    path: ~/.zshrc
    line: "{{ item }}"
    state: present
  loop:
    - eval "$(direnv hook zsh)"
