- name: Update homebrew # noqa package-latest
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
    - brew

- name: Add custom brew taps
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ homebrew_taps }}"
  tags:
    - brew

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_packages }}"
  tags:
    - brew

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
  tags:
    - brew

- name: homebrew cleanup # noqa no-changed-when
  command: brew cleanup
  tags:
    - brew
