- name: Setup workdirs
  import_tasks: directories.yml
  
- name: Install things
  import_tasks: installs.yml

- name: Setup basic dotfile config
  import_tasks: dotfiles.yml

- name: Run config commands
  import_tasks: config.yml