#!/usr/bin/env ansible-playbook
- hosts: mac
  connection: local
  tasks:
    - name: Check if workdir is the right dir
      debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/mac-ansible')

- hosts: mac
  connection: local
  roles:
    - config_setup
